---
- hosts: all
  vars:
    local_user: dave
    game_user: djdjango
    local_user_dir: /home/{{local_user}}
    game_user_dir: /home/{{game_user}}
  remote_user: root

  tasks:

  - name: Ensure djdjango user exists 
    user: name={{game_user}} comment="Django User"
 
  - name: Ensure postgres user exists 
    user: name=postgres
 
  - name: ensure djdjango's .ssh directory exists
    file: path=/home/{{game_user}}/.ssh 
          state=directory mode=0700
          owner={{game_user}} 
 
  - name: Ensure ssh passwordless logins work 
    copy: src={{local_user_dir}}/.ssh/id_rsa.pub 
          dest={{game_user_dir}}/.ssh/authorized_keys
          owner={{game_user}}
          mode=600

  - name: Ensure ssh config good
    lineinfile: dest=/etc/ssh/sshd_config
                line="PermitRootLogin no"
                state=present
    lineinfile: dest=/etc/ssh/sshd_config
                line="Protocol 2"
                state=present

  - name: set up django environment variables
    lineinfile: dest=/home/{{game_user}}/.bashrc
                regexp="PYTHON_PATH"
                line="export PYTHON_PATH=~/dev/newdominion"
                state=present
    
    lineinfile: dest=/home/{{game_user}}/.bashrc
                regexp="DJANGO_SETTINGS_MODULE"
                line="export DJANGO_SETTINGS_MODULE=dg.settings"
                state=present

  - name: Ensure apt cache is up to date
    apt: update_cache=yes

  - name: Ensure system packages are up to date
    apt: upgrade=dist update_cache=yes

  - name: ensure system packages are installed
    apt: name={{item}} state=latest
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2
      - redis-server
      - python-pip
      - python-dev
      - build-essential
      - libgeos-dev
      - git
      - unattended-upgrades
      - postgresql
      - libpq-dev
      - python-psycopg2

  - name: Ensure pip packages are installed
    pip: name={{item}} state=latest
    with_items:
      - Django
      - django-markdown-deux
      - django-markup-deprecated
      - django-registration
      - markdown2
      - markup
      - MarkupSafe
      - paramiko
      - redis
      - Shapely
      - gunicorn
      
  - name: install source from github
    git: repo=https://github.com/dav3xor/daves-galaxy.git
         dest=/home/{{game_user}}/dg

  - name: copy server settings.py file
    template: src=./ansible_files/settings.py
              dest=/home/{{game_user}}/dg/settings.py
- hosts: all
  sudo: yes
  sudo_user: postgres
  remote_user: root
  gather_facts: no

  vars:
    dbname: dg
    dbuser: django
    dbpassword: djangopass

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
      


