#!/bin/bash
cd /home/djdjango/newdominion
git pull git@github.com:erikh/davesgalaxy.git
sleep 2
killall -e "python2 manage.py runfcgi host=127.0.0.1 port=8080 --settings=settings"
python2 manage.py runfcgi host=127.0.0.1 port=8080 --settings=settings

